### ISSUE TITLE
Issues working in Chrome for a tree view

### ISSUE THREAD

**Issue by amarpreethora** [ds82/angular-contextmenu#2]
Hi Dennis, 
I would like to thank you for this awesome code. I am using this context menu in my project where i have a data in the tree view.
Like I have 'Cases' as first level of hierarchy. Inside cases I have multiple 'Samples'. Inside samples i have multiple 'Analysis'. 

I have implemented context menu like this for every level of the tree - 
Sample Picture of menus-
![sample](https://cloud.githubusercontent.com/assets/12627591/7880185/ec94fd16-0614-11e5-812f-424a6da16a5d.png)

I have assigned 'context1', 'context2', 'context3' as Ids to each level of 'ul' so as to differentiate each of them as different menus.

It works fine in Firefox however In chrome when I do right click on Analysis, it opens the menu but when I do right click on Sample, it opens the menu on sample but the existing open menu on analysis does not get close. Now if I do right click on Cases which is first level of hierarchy, it will open another menu keeping previous two in open status.

In mozilla when I open menu on upper hierarchy level, it closes the menu on lower hierarchy level automaticaly. 

I am not able to find the root cause. It is like chrome is not supporting something in your code?
Any kind of help will be appreciated. Thanks!

**Comment by amarpreethora** [comment]
Here is the sample menu on Chrome. Whereas It is working fine on Mozilla.
![sample](https://cloud.githubusercontent.com/assets/12627591/7880055/a8d9b55e-0613-11e5-81fe-cd08adcbf2c8.png)

**Comment by ds82** [comment]
thanks for your comment and your bug report! :)
I'll try to reproduce your bug to find a solution. If you could provide a jsbin or similar it would help a lot.

**Comment by amarpreethora** [comment]
Thanks Dennis for revert. Currently I am sick with fever. I will reply you
with jSbin once I am fine. :-)

Thanks a lot.

Amarpreet

**Comment by ds82** [comment]
get well soon!

in the meantime, I hope I found your bug.
If it remains pls reopen.
