### ISSUE TITLE
Bower package not working

### ISSUE THREAD

**Issue by warapitiya** [ds82/angular-contextmenu#4]
what is the correct bower module?

**Comment by ds82** [comment]
There is no bower package at the moment ..

**Comment by ds82** [comment]
I fixed bower.json .. you should be able to install the package via bower with a git endpoint:

bower install git://github.com/ds82/angular-contextmenu#0.1.2

sadly, the bower package `angular-contextmenu` ist registered with another user even though he has no valid repo behind it. I'll fill a bug in his repo, maybe he unregisters the name.

**Comment by ds82** [comment]
Thanks to @tgelu for unregistering his package; this module is now available in bower via
```
bower install angular-contextmenu
```
