### ISSUE TITLE
bug while changing the whole table

### ISSUE THREAD

**Issue by topazbor** [ds82/angular-contextmenu#59]
when I'm making a table with 
`<tr ng-repeat="item in items" contextmenu-item="item">`

it's working good and the item is correct.
but when I change the $scope.items in the js, the table changes but the context-menu is still referring to the old context-menu list!

how to solve it?
I have tired to delete the whole context menu list, but it is not building the list again.

**Comment by topazbor** [comment]
?

**Comment by ds82** [comment]
I'm looking into this as soon as I can ..

**Comment by topazbor** [comment]
any luck?

**Comment by ds82** [comment]
Sorry I cannot reproduce your error. Pls have a look at this bin:
http://jsbin.com/lijatidivu/edit?html,js,output

The data updates if you hit the button and the contextmenu shows the correct values.
Could you pls provide a bin to demo your error?

**Comment by topazbor** [comment]
the problem was that my item list was a dict and not a list..
when I chnage it to list it works prefect
thanks for help
